version: '2.4'
services:
  vroom:
    image: vroomvrp/vroom-docker:v1.11.0
    container_name: vroom_server
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=osrm
    ports:
      - 3000:3000
    depends_on:
      - osrm

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: >
      bash -c "rm -rf data && osrm-extract -p /opt/car.lua /data/portugal-latest.osm.pbf && \
      osrm-partition /data/portugal-latest.osrm && \
      osrm-customize /data/portugal-latest.osrm && \
      osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/portugal-latest.osrm"
